### ISSUE TITLE
Need some corrections

### ISSUE THREAD

**Issue by makenahub** [melo-gonzo/StockDataDownload#1]
Hi there.
Thank you for your code! 
But there are a few of issues appeared to me while using it:

1) The script doesn't download all historical period data for ^GSPC index (S&P500), only starting from 1970s. It's a pity because ^GSPC has a longer data starting from 1927s. This issue appears the same way for ^DJI. 

2) **--add_tickers** argument doesn't work properly on my side and returned: **Traceback (most recent call last):
  File "download_data.py", line 222, in <module>
    main()
  File "download_data.py", line 209, in main
    check_arguments_errors(args)
  File "download_data.py", line 204, in check_arguments_errors
    raise (ValueError("Invalid ticker_location path {}".format(os.path.abspath(args.weights))))
AttributeError: 'Namespace' object has no attribute 'weights'**

Could you fix them? 
THX in advance!

**Comment by melo-gonzo** [comment]
Hello @makenahub . Unfortunately I cannot change the amount of data that yahoo-finance can provide to you. I have the code set to give back the max amount.

For your second question - please make sure you have created the ticker_location as described in the readme. Once you do that, update the default location inside of the code itself on line 184. You should have no problems downloading data after doing this.

Thanks.

**Comment by makenahub** [comment]
I see, and for the second - it now works.
Thank you!
